name: Node.js Check

on:
  push:
    branches:
      - main

jobs:
  node-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify Node.js
        run: node -v

      - name: Verify npm
        run: npm -v
